### ISSUE TITLE
No sinc closed event when connection is lost.

### ISSUE THREAD

**Issue by aliher1911** [librespot-org/librespot#600] opened 2021-02-11 23:30 UTC
I sometimes experience connection issues where librespot loses connection:
ERROR librespot_core::session] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
and playback is stopped.

In that case sink closed event is not generated.
I'm using those events to power off speakers when there's no playback and turn them back on when sink start event arrives. So if connection drops, monitoring program keeps everything powered. It would be helpful to either send sink stop or some other event indicating that playback was stopped.

**Comment by sashahilton00** [comment] 2021-02-12 02:34
Related to #134

**Comment by roderickvd** [comment] 2021-05-24 21:20
Will be fixed when we get the new API in, which is factoring in reconnection support from the ground up.

**Comment by roderickvd** [comment] 2021-06-14 10:28
Duplicate of #276.

**Closed by roderickvd** 2021-06-14 10:28 UTC
Labels: bug, duplicate, new api
