### ISSUE TITLE
Librespot error sending packet Os

### ISSUE THREAD

**Issue by lakomyt** [librespot-org/librespot#918] opened 2021-12-29 13:02 UTC
I am using librespot in [raspotify](https://github.com/dtcooper/raspotify/) and it doesn't work.

Error message is:
`librespot[26936]: [2021-12-29T12:58:43Z WARN  libmdns::fsm] error sending packet Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }`

**Comment by roderickvd** [comment] 2021-12-29 19:51
Duplicate of #326.

**Comment by roderickvd** [comment] 2021-12-29 19:52
Duplicate of #326

**Closed** 2021-12-29 19:52 UTC
Labels: duplicate, invalid
