### ISSUE TITLE
ERROR does not kill process

### ISSUE THREAD

**Issue by Northo** [librespot-org/librespot#241] opened 2018-07-29 19:52 UTC
I get  
`ERROR:librespot_core::session: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer"`
but the process does not exit, so systemd does not restart it. 

In the spotify client librespot will sometimes show up, sometimes not. If I select the speaker after the ERROR (if it shows in the client), the speaker eventually disappears from the client, and I have to manually restart the process on the server.

This might be a duplicate of #226, but this is not a panic, therefore I leave that decision up to someone who knos more than me.

Raspberry Pi 2 model B, running Arch Linux

**Comment by michalfita** [comment] 2018-08-15 20:07
Yes, this is still a problem.

**Comment by michalfita** [comment] 2018-10-23 20:10
@wfraser You seem to be very fluent in all this multiprocess/multithreading task - could you try to solve this issue? Reproduction requires disconnection of broadband during playing - should be easy to reproduce on virtual machine.

**Comment by sashahilton00** [comment] 2018-11-03 15:29
This is a well known bug, currently being tracked at https://github.com/librespot-org/librespot/issues/134. The problem is that it requires a significant rewrite of parts of librespot, and hence hasn't been fixed. Anyone is welcome to give it a go, in the meantime, closing this in favour of aforementioned issue.

**Closed by sashahilton00** 2018-11-03 15:29 UTC
