### ISSUE TITLE
Error while installing from cargo

### ISSUE THREAD

**Issue by EliteDaMyth** [librespot-org/librespot#492] opened 2020-06-13 14:54 UTC
Input: cargo install librespot

Error:
```
error[E0308]: mismatched types                                                                                                                              
  --> C:\Users\Akshat\.cargo\registry\src\github.com-1ecc6299db9ec823\librespot-protocol-0.1.1\build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> C:\Users\Akshat\.cargo\registry\src\github.com-1ecc6299db9ec823\librespot-protocol-0.1.1\build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::String`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `librespot-protocol`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `librespot v0.1.1`, intermediate artifacts can be found at `C:\Users\Akshat\AppData\Local\Temp\cargo-installpFSihW`

Caused by:
  build failed
```

**Comment by ashthespy** [comment] 2020-06-13 15:34
Dupe of #477 and others mentioned there..

**Closed by ashthespy** 2020-06-13 15:34 UTC
