### ISSUE TITLE
error[E0308]: mismatched types, white compiling

### ISSUE THREAD

**Issue by iTeeLion** [librespot-org/librespot#503] opened 2020-07-21 07:16 UTC
**cargo install librespot**
```
Compiling librespot-protocol v0.1.1
error[E0308]: mismatched types
  --> /home/iteelion/.cargo/registry/src/github.com-1285ae84e5963aae/librespot-protocol-0.1.1/build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> /home/iteelion/.cargo/registry/src/github.com-1285ae84e5963aae/librespot-protocol-0.1.1/build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::String`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `librespot-protocol`.
```

**Comment by ashthespy** [comment] 2020-07-21 13:39
Dupe of #477 and others mentioned there..

**Closed by ashthespy** 2020-07-21 13:39 UTC
