### ISSUE TITLE
Does anyone need to reset their password every 7 days？

### ISSUE THREAD

**Issue by SuperYogurt** [librespot-org/librespot#1374] opened 2024-10-17 12:19 UTC
My account prompts me to reset my password after 7 days

**Comment by kingosticks** [comment] 2024-10-17 12:22
Duplicate of https://github.com/librespot-org/librespot/discussions/1311

Plus this needs way more context, pretty much all the information in the bug report template that you didn't use.

**Closed** 2024-10-17 13:49 UTC
Labels: bug
