### ISSUE TITLE
[Rodio][Windows] Playback stuttering 

### ISSUE THREAD

**Issue by ashthespy** [librespot-org/librespot#317] opened 2019-03-22 16:02 UTC
Testing with my win10 box - I seem to have some stuttering issues when I start multitasking a bit. 

@willstott101 Any debug/profiling options I can turn on to get more info?

**Comment by willstott101** [comment] 2019-03-22 18:16
Hm, not that I know of. You could try increasing the buffer size? Maybe we should expose that as a cmdline arg for all backends

**Comment by willstott101** [comment] 2019-03-25 18:08
Hm, I have noticed some lack of playback smoothness when using a debug build on my laptop

**Comment by willstott101** [comment] 2019-03-25 18:08
I wonder if there's a buffer beyond librespot which we can increase, reducing the buffer size that we're explicitly creating.

**Comment by willstott101** [comment] 2019-03-25 19:40
As far as I can tell from the [CPAL source](https://github.com/tomaka/cpal/blob/master/src/wasapi/stream.rs#L293) and [Windows docs](https://docs.microsoft.com/en-us/windows/desktop/api/Audioclient/nf-audioclient-iaudioclient-initialize) is that CPAL uses the minimum buffer size.

I've stuck an `info!()` which prints when number of chunks in the Rodio Sink's queue is < 6 and I'll see if I notice any audio problems again, and if that's been printing out when I do.

If that doesn't provide evidence that it's Librespot-side I might have a go at specifying a buffer size for the Windows client in CPAL.

**Comment by ashthespy** [comment] 2019-03-26 16:48
I had some improvements increasing the buffer size on my debug build. However, shouldn't there be a method to set something akin to alsa's `start_threshold`? That should allow for some flexibility, instead of exposing another parameter to the end user?

**Comment by sashahilton00** [comment] 2019-04-17 02:16
any further troubleshooting on this? Have tried to reproduce in a throttled VM, but no luck yet...

**Comment by willstott101** [comment] 2019-05-25 13:06
Not really had any luck with this. As mentioned here https://github.com/librespot-org/librespot/pull/314#issuecomment-495916619 my CPAL-direct backends still struggle under heavy load.

**Comment by willstott101** [comment] 2019-09-08 12:30
I think the requirement of a second thread might be part of the problem here. As I don't think that thread is given higher priority (though I haven't confirmed).

There's some movement towards improving the CPAL API in https://github.com/RustAudio/cpal/issues/278 so I propose helping/waiting  for those changes before trying again.

**Comment by ashthespy** [comment] 2019-11-06 17:45
@willstott101 was playing around again, and hit this again. It is also aggravated when using a bluetooth audio device. Will try running a profiler and take a deeper look.

**Comment by willstott101** [comment] 2019-11-06 19:30
I've updates the cpal-backend2 branch above to use the newer cpal API, I suspect this won't help much but it'd be good if you could try that branch out

**Comment by strafe** [comment] 2020-11-21 23:03
@ashthespy is there any chance the `rodio` version could be bumped? There's a crackling issue on macOS that was likely fixed in the latest release - https://github.com/RustAudio/rodio/pull/320

**Comment by willstott101** [comment] 2020-12-06 12:18
@strafe Does my branch above using latest rodio help?

**Comment by Johannesd3** [comment] 2021-01-27 11:18
I created a simple crate that does not use librespot_playback and feeds the vorbis audio of a single track directly into rodio: https://github.com/Johannesd3/librespot-player. Does this increase performance? At least I had no issues on Windows. Then maybe it's a matter of implementation.

**Comment by strafe** [comment] 2021-03-06 07:01
> @strafe Does my branch above using latest rodio help?

@willstott101 spotifyd finally bumped librespot to `0.1.5` and cut a new release a couple days ago. Sadly Rodio still crackles on most songs. It's really unfortunate since it makes any combination of spotify-tui and spotifyd pretty much unusable on macOS.

**Comment by Johannesd3** [comment] 2021-03-21 12:43
If I understand everything correctly, there are to problems:

The first is our rodio backend. Currently, it allocates a new buffer every time a new packet arrives. This could become faster using a spsc queue/ring buffer.

But cpal and alsa don't really fit: Cpal is callback-based while alsa uses an internal ring buffer. Therefore, cpal spawns an extra thread just to copy the data from our buffer to alsa's buffer.

The best solution imo is to make alsa the default backend on linux again.

**Comment by roderickvd** [comment] 2021-03-21 13:21
Oh yes. Still hunting down why Rodio on Alsa is broken in so many cases. While I appreciate the "black-box" approach of librespot sinking into a "one size fits all" backend, it's just not there yet.

**Comment by roderickvd** [comment] 2021-06-14 10:23
Cannot reproduce anymore on macOS and no further replies. There have been a lot of updates to `librespot`,  `cpal`, and Rodio since this was reported. Feel free to reopen if this is still an issue on the latest version.

**Closed by roderickvd** 2021-06-14 10:23 UTC
Labels: audio

**Comment by strafe** [comment] 2021-06-16 22:01
This seems to be working in the latest version of `ncspot`.

`spotify-tui` (`spotifyd`) is probably still broken since they're depending on an older version of librespot for now. Thanks everyone who worked on this!
