### ISSUE TITLE
allow binding to LAN address instead of 0.0.0.0 for zeroconf

### ISSUE THREAD

**Issue by ayushnix** [librespot-org/librespot#887] opened 2021-11-23 17:28 UTC
It seems like librespot binds to all interfaces (0.0.0.0) by default for zeroconf discovery.

Pardon my ignorance but does it need to bind to all interfaces for zeroconf discovery? Would it be possible to bind it to the assigned LAN address (such as 192.168.1.2) and still have the Spotify Discovery feature (which is what zeroconf is used for?) work as expected? If yes, can we get an option to change the address to which librespot binds to for zeroconf?

I've raised a [similar issue](https://github.com/Spotifyd/spotifyd/issues/990) in the spotifyd repository as well.

**Comment by roderickvd** [comment] 2021-11-23 18:38
Duplicate of #486.

**Closed by roderickvd** 2021-11-23 18:38 UTC
Labels: duplicate
