### ISSUE TITLE
Fails to build correctly with `arm-unknown-linux-musleabihf` target and rust > v1.21

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#328] opened 2019-04-09 16:08 UTC
I used to successfully compile librespot on a Pi3 with the "arm-unknown-linux-musleabihf" target. Up until a few months ago this was fine. Then the requirement for some rust later than 1.21 was introduced. And I never succeeded building for that target again. As soon as I use a more recent rust environment the binary would fail to run. It's not even considered a statically linked binary any more:

```
$ file target/arm-unknown-linux-musleabihf/debug/librespot
target/arm-unknown-linux-musleabihf/debug/librespot: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /usr, BuildID[sha1]=dfa1ae4ddd017f8ad9b084905e2eedad079ecf8d, not stripped
```

Trying to run it I'd get the rather generic "file or folder not found" message:

```
$ target/arm-unknown-linux-musleabihf/debug/librespot
bash: target/arm-unknown-linux-musleabihf/debug/librespot: Datei oder Verzeichnis nicht gefunden
```

What's wrong with this file? I noticed that during the build I would at some point get the following message:

```
warning: dropping unsupported crate type `cdylib` for target `arm-unknown-linux-musleabihf`
```

Could this be the reason for the failure?

FWIW: I'm successfully linking against musl on i386 and x86_64.

**Comment by CodeCutterUK** [comment] 2019-04-10 18:57
I'm building on 1.31.1 without issue, however I had been on commit daeeeaa122fc2d71edf11e562e23038db4210b39
So I suspect it isn't the version. Equally I'm building as `arm-unknown-linux-gnueabihf`

Moving to master, currently 14721f45fe7e3e5427abdfdedca6ed1ec8948d80 , seems to break things......I'm yet to go through and find which commit breaks it, but initial debugging suggests that updating the dependant packages may have introduced a package/version that doesn't build on ARM correctly.

**Comment by michaelherger** [comment] 2019-04-10 20:17
See my last paragraph: musl linking does work on i386 and x86_64 for me, too. As well as arm-unknown-linux-gnueabihf and half a dozen other platforms. It's really only muslabihf that's causing problems. And this used to work until Rust 1.21. It still works for a simple "Hello World" and Rust 1.33. I guess it's some crate librespot is using which is no longer supported. But how could I figure out which one it is?

**Comment by ashthespy** [comment] 2019-04-10 21:44
While compiling, try running cargo in verbose mode with `--verbose`  to help debug if you haven't already.

**Comment by CodeCutterUK** [comment] 2019-04-12 09:46
Just a quick update - switching to `armv7-unknown-linux-gnueabihf` from `arm-unknown-linux-gnueabihf`fixed my issues

`arm-unknown-linux-gnueabihf` worked up until e9b159e9d9990eb4674482f76a46bf53fbaa664f I haven't dug into the detail

**Comment by sashahilton00** [comment] 2019-04-17 02:10
let us know if you identify the cause of the issue - we don't really hve the resources to test cross all platforms, hence armv6 probably slipped through the net. If there is a quick fix we can look at implementing it.

**Comment by PKizzle** [comment] 2019-05-13 19:16
The warning  `dropping unsupported crate type cdylib for target arm-unknown-linux-musleabihf` is caused by lewton v0.9.4

**Comment by PKizzle** [comment] 2019-05-13 20:49
I was able to remove the warning by adding `-C target-feature=-crt-static` to the rustc command

**Comment by PKizzle** [comment] 2019-05-14 18:37
Using `-C target-feature=-crt-static -C link-arg=-lm -C link-arg=-ldl -C link-arg=-lpthread`
I am able to successfully build, but receive the following error message when trying to execute:
```
thread '<unnamed>' panicked at 'failed to allocate an alternative stack', src/libstd/sys/unix/stack_overflow.rs:136:13
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: main
   8: __libc_start_main
fatal runtime error: failed to initiate panic, error 9
Aborted (core dumped)
```
So it seems to be an internal rust issue...

**Comment by ashthespy** [comment] 2020-03-20 22:50
Is this still an issue with the current version? 
@michaelherger @PKizzle

**Comment by PKizzle** [comment] 2020-03-20 23:05
No, I was able to compile successfully with newer versions of librespot. Just one thing I noticed: I have to specify `--no-default-features --features rodio-backend` for the compilation to succeed. The default build option somehow don’t work for me.

**Comment by ashthespy** [comment] 2020-03-21 09:26
That is interesting, `default` should be `libmdns` + `rodio`, so looks like `libmdns` isn't playing well with your target?

**Comment by PKizzle** [comment] 2020-04-13 17:31
I tried again and with updated dependencies the whole project can be successfully compiled for `arm-unknown-linux-musleabihf`. The issue may hereby be closed. 
Used compilation arguments:
```
RUSTFLAGS="-C link-args=-Wl,-rpath-link,/lib -C target-feature=-crt-static" PKG_CONFIG_PATH=/usr/lib/pkgconfig PKG_CONFIG_ALLOW_CROSS=1 cargo build --release
```

**Comment by ashthespy** [comment] 2020-04-13 19:20
@PKizzle  Could you add an entry to the [wiki](https://github.com/librespot-org/librespot/wiki/Cross-compiling) if you think this needs some special hints to get compiled?

**Comment by PKizzle** [comment] 2020-05-07 16:25
@ashthespy I added it to the wiki. Could you please review the changes?

**Comment by ashthespy** [comment] 2020-05-07 16:57
@PKizzle Thanks, if you could add a note about `musleabihf` as well it would be superb..
In the meantime, will mark this as fixed.

**Closed by ashthespy** 2020-05-07 16:57 UTC
Labels: compilation

**Comment by PKizzle** [comment] 2020-05-07 18:55
I added a note which target is meant by armv6
