### ISSUE TITLE
Cant start a new playlist when playing

### ISSUE THREAD

**Issue by simba83** [librespot-org/librespot#298] opened 2019-03-10 13:44 UTC
If i use a playlist and want to start a new playlist that cant be done from Spotify (Android or Windows).
It works if i change output to local device (android or windows) and start a new playlist and after this change the output to librespot again.
I might do something wrong or it could be a little bug.

**Comment by kingosticks** [comment] 2019-03-10 14:45
Are you sure you are using the latest version?

**Comment by simba83** [comment] 2019-03-10 14:52
Built it yesterday from master repo

**Comment by sashahilton00** [comment] 2019-03-11 19:39
Can confirm this is a bug, just tried it and got the same behaviour. When connected to librespot, one can create a playlist and add songs, but any attempt to play the new playlist via librespot causes the currently playing track to either restart or jump back a seemingly random amount. 

At a wider level, playback appears to break after adding a playlist and attempting to use librespot; attempting to select a different song/album/etc. just causes the next song in the queue to play. I suspect we will need to do some reverse engineering of Protobuf again.

**Comment by jbmerhner** [comment] 2019-04-02 16:39
hello, I'm really looking for solution for this issue. I'm just curious if there is any chance this will be checked ?

**Comment by haja** [comment] 2019-11-01 11:20
it seems this bug is still open.
is there any way one can help?

**Comment by willstott101** [comment] 2019-11-01 12:17
I can't reproduce this myself.

Librespot seems quite happy playing a freshly made playlist on `dev` branch on Windows.

Are you seeing this happen with a new build @haja ?

**Comment by roderickvd** [comment] 2021-08-07 20:26
Closing, no further feedback.

**Closed by roderickvd** 2021-08-07 20:26 UTC
Labels: bug, reverse engineering
