### ISSUE TITLE
Librespot playback won't work

### ISSUE THREAD

**Issue by thgilciffart** [librespot-org/librespot#1273] opened 2024-04-09 09:45 UTC
**Describe the bug**
Playback will not work no matter what. I tried spotify qt , official spotify client, spotify web , spotify on phone and to no avail does it work at all.  It shows the song is playing however, there is no sound.

**To reproduce**
1.  Clone official librespot repo
2. Use mingw64 and install rust with `pacman -S mingw-w64-x86_64-rust`
3. cargo build --release
4. cd to ./target/release/librespot
5. Run librespot -n "Librespot" -b 320 -c ./cache --enable-volume-normalisation --initial-volume 75 --device-type avr
6. Use spotify client to control librespot

**Log**
A full log so we may trace your problem (launch `librespot` with `--verbose`). Format the log as code.
[log.txt](https://github.com/librespot-org/librespot/files/14916851/log.txt)

**Host (what you are running `librespot` on):**
- OS: W11
- Platform: x64 b550

**Additional context**
My output is to a  headset is a razer barracuda x connected with usb.

**Comment by kingosticks** [comment] 2024-04-09 10:00
The log shows your error. This is a duplicate of https://github.com/librespot-org/librespot/issues/1179

**Comment by roderickvd** [comment] 2024-09-16 17:50
Duplicate.

**Closed by roderickvd** 2024-09-16 17:50 UTC
Labels: bug
