### ISSUE TITLE
Panic on an `Err` value: InitialFileHeadersCorrupt

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#35] opened 2018-01-29 14:18 UTC
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Oct 08, 2016 at 08:53 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/121_

----

Sometimes, librespot panics with:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InitialFileHeadersCorrupt', src/libcore/result.rs:799
```

This issue happens if a track is loaded in the Spotify Connect Client (so I can see the cover and the track artists and song title), but is not played locally (but was played before). Then I start librespot on my embedded Linux device, connect the client with librespot and after 3 or 4 seconds the panic happens.

Note, I am using Tremor as ogg decoder.

**Comment by sashahilton00** [comment] 2018-01-29 14:19
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Wednesday Oct 12, 2016 at 18:48 GMT_

----

Not sure why [OV_EINVAL](https://github.com/plietar/rust-tremor/blob/master/src/lib.rs#L266) is described as [InitialFileHeadersCorrupt](https://github.com/plietar/rust-tremor/blob/master/src/lib.rs#L36) whereas  [vorbis-errors](http://www.fifi.org/doc/libvorbis-dev/vorbis-errors.txt) describes it as:

> OV_EINVAL       Invalid argument value.

**Comment by sashahilton00** [comment] 2018-01-29 14:19
<a href="https://github.com/herrernst"><img src="https://avatars2.githubusercontent.com/u/20795?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrernst](https://github.com/herrernst)**
_Tuesday Dec 20, 2016 at 21:58 GMT_

----

Hm, I've just cross-compiled the current master for Raspberry Pi and *always* got `InitialFileHeadersCorrupt`, not yet found out the cause (not using Tremor btw)

**Comment by sashahilton00** [comment] 2018-01-29 14:19
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Wednesday Dec 21, 2016 at 06:49 GMT_

----

Maybe this one helps: https://github.com/joerg-krause/librespot/commit/b58dc0b54e719101205dcd972062334cc72849db

**Comment by sashahilton00** [comment] 2018-01-29 14:19
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Saturday Dec 31, 2016 at 11:59 GMT_

----

I've cherry picked @joerg-krause's commit (thanks btw).
Since I can't reproduce this I'm not too sure how to fix the root cause.

**Comment by ComlOnline** [comment] 2018-01-29 23:36
Closed as it was very old and Paul couldn't reproduce.

**Closed by ComlOnline** 2018-01-29 23:36 UTC
Labels: can't reproduce, imported
