### ISSUE TITLE
Stuttery or choppy audio on Raspberry Pi

### ISSUE THREAD

**Issue by lumaxis** [librespot-org/librespot#532] opened 2020-10-19 14:03 UTC
For a few weeks now, I've been observing occasional stuttering or choppy audio when playing music via my Raspberry Pi Zero W whereas it used to fork flawlessly in the beginning.

I recently started running another service on the Pi but the timeline doesn't really align with when I started experiencing these issues. I monitored `top` for a little bit and also didn't see any correlation between CPU usage and the choppiness.

Is there anything I can do to debug or understand why this might be happening? Appreciate any help!

**Comment by JasonLG1979** [comment] 2020-10-25 22:50
I also run librespot (via raspotify) on a Raspberry Pi Zero W. I use my Pi Zero as a Spotify Connect appliance so I've stripped it down to the bare minimum even then though I can get CPU spikes of 60 - 70% while librespot is fetching a song.

In general stuttering or choppy audio is usually caused by a buffer underrun. Off the top of my head the easiest things to try are:

1. Don't resample librespot. ALSA's default sampling rate is 48000 so if you're going to the "default" input. Audio from librespot will be upsampled to 48000 (it's 16 bit 41000).

2. Increase the buffer size from 0.5 sec to 1 sec.

3. Drop the Niceness of librespot so it has a higher priority.

4. Drop the quality from 320 to 160. 160 for some reason uses a little bit less CPU on my Pi.

5. If the other service is audio then stop that service before you start playback with librespot with a hook script.

**Comment by roderickvd** [comment] 2021-03-12 23:07
Also make sure you've compiled with `--release`.

**Comment by lumaxis** [comment] 2021-03-12 23:11
I have since moved from a Raspberry Pi Zero W to a 4 (for other reasons), where I have not seen this anymore. I'm fine to close this as long as nobody else still has an interest to track this issue.

**Comment by Emgalai** [comment] 2021-04-19 10:02
I installed Librespot service addon on top of LibreELEC 9.2.6 on Raspberry 1 B+ and the audio is so stuttery it is completely unusable. It is not just occassional stuttering, it is constant stuttering. I don't know how to test the options suggested by JasonLG1979 on LibreELEC (I was able to set the niceness level, but not the rest).

I have IQaudio DAC+ on the Pi. The audio stutters the same if I use IQaudio or the HDMI output.

**Comment by JasonLG1979** [comment] 2021-04-19 17:48
@Emgalai 

A Raspberry Pi 1 B+ is basically the same thing as a Pi Zero. Do you actually use the UI bits and if so is Kodi even usable on a Pi 1? Audio is kinda heavy. For the most part any sort of upsampling is a no go on a Pi 1/Zero if you plan on doing absolutely anything else on it. If I had to guess kodi is doing some resampling. Running librespot via the command line is probably bypassing that resampling.

**Comment by Emgalai** [comment] 2021-04-20 11:19
> Do you actually use the UI bits and if so is Kodi even usable on a Pi 1?

I have used Kodi on RPi 1 B+ since it was released in 2014 and most of my video files work without any problems. For music I have used mpd on the same RPi, without any problems. I have even run some surround audio files through mpd and remixed them to stereo without any problems (My mpd setup has the audio output set to have two channels). Maybe having the IQaudio DAC on the RPi is helping for that, I don't know.

**Comment by JasonLG1979** [comment] 2021-04-20 22:30
@Emgalai I don't mean down mixing I mean resampling specifically upsampling. Like converting from 44.1 kHz to 48 kHz on the fly during playback.

**Comment by Emgalai** [comment] 2021-04-22 06:13
I tried limiting sample rate of Kodi to 44.1 kHz, in case the Kodi addon uses the Kodi settings, but it did help. How could I know if resampling is done or not?

**Comment by JasonLG1979** [comment] 2021-04-22 18:26
`period_size:` and `buffer_size:` are also relevant to make sure the buffer is large enough for smooth playback.

**Comment by JasonLG1979** [comment] 2021-04-22 18:30
Drop outs are generally the result of of the CPU not being able to keep up. Either because the buffer is to small or because it can't handle whatever processing is being done to the audio, or a combination of both.

**Comment by roderickvd** [comment] 2021-05-24 21:22
Closing this as this seems to be an issue in `Kodi` downstream.

**Closed by roderickvd** 2021-05-24 21:22 UTC
Labels: audio, wiki

**Comment by Mysonemo** [comment] 2024-02-12 13:05
I've found the solution here by disabling the normalization.
https://github.com/dtcooper/raspotify/issues/504
