### ISSUE TITLE
Latest spotify android client (v8.4.42.722) does not detect librespot

### ISSUE THREAD

**Issue by romqu** [librespot-org/librespot#176] opened 2018-03-01 18:22 UTC
Hello everybody,

first off all, thank you for the great project, I really appreciate the work you're doing.

I recently updated the android client to the newest version and since then it has stopped to list librespot
as an available device. It does work with the previous one (v8.4.39.673) though.
I'm using a Galaxy S6 (LineageOS 14.1) and librespot (build from master today) is running on a raspberry pi 3 with the latest moode os.
Maybe the issue is on my end, but I haven't changed anything in my setup line besides upgrading to the latest librespot version.

I apologize in advance if I have missed something.

**Comment by awiouy** [comment] 2018-03-02 11:52
This should be fixed by #167 
Do you have a log?

**Comment by romqu** [comment] 2018-03-03 09:05
Hello,

thank you for the reply.
> Do you have a log?

I suppose you mean a log from the spotify application?
I already took a look at the logcat but couldn't find anything useful.
But I can of course provide one.

In the case of a librespot log, I executed the following command.
` RUST_BACKTRACE=1 librespot --name name --backend alsa --verbose`

Due to the fact that it doesn't show up in the application, there is no other output than:
`INFO:librespot: librespot 8f8eb8c (2018-02-28). Built on 2018-02-28. Build ID: FL46vJJ7
DEBUG:librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:0`

But I get the feeling the issue is on my end, since I seem to be the only one that does experience the problem.
I will just keep an eye on it and do some further testing.

**Comment by aopst** [comment] 2018-03-03 12:18
My Spotify updated yesterday too. The device shows up in the devices tab, but as soon as I choose it, it crashes.
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
DEBUG:librespot::spirc: drop Spirc[0]
DEBUG:librespot::player: drop Player[0]
DEBUG:librespot_core::session: drop Session[0]
DEBUG:librespot_core::mercury: drop MercuryManager
DEBUG:librespot_core::session: drop Dispatch
`

**Comment by sashahilton00** [comment] 2018-03-03 13:41
@aopst that issue was resolved in #167. Rebuild librespot with the latest commit and it'll work again. 
@romqu I'm inclined to agree that the issue is likely on your end. To test this, could you start librespot with ```-u YOUR_USERNAME``` added, and login manually. If the device then shows up and you are able to play music to it from the spotify app, then that isolates the problem to your network at least.

**Comment by romqu** [comment] 2018-03-03 17:37
@sashahilton00 
Indeed, it works with the username and password supplied. But discovery mode does not work. Only with the previous android version. Really weird.
Anyway, I apologize for the inconvenience.

**Closed** 2018-03-03 17:37 UTC

**Comment by jollybully** [comment] 2018-04-18 23:29
@romqu - I'm having the same problem when using the Spotty fork of librespot and am at my wits end, I'm beginning to think it's a network issue on my end and would be interested to know if you ever found a solution?

**Comment by michaelherger** [comment] 2018-04-19 05:35
@jollybully - some users mentioned they had to to wipe the Spotify app's data/cache. And make sure you enable local discovery or disable local only discovery in the app.

Did you get in touch with me on forums.slimdevices.com?

**Comment by DarkNinja77** [comment] 2019-09-16 21:29
I have the same problem for about a year and still have it. Librespot doesnt show up as a device to play to.
