### ISSUE TITLE
repeating single track is not possible

### ISSUE THREAD

**Issue by eladyn** [librespot-org/librespot#984] opened 2022-04-12 19:36 UTC
*This report is primarily coming from https://github.com/Spotifyd/spotifyd/issues/1071, which I noticed, is also an issue with the current dev version as well as with the `new-api` branch.*

# Description

Librespot devices don't support setting the repeat type to `single track`, only `off` or `all`. In the official client (Linux and Android at least), the repeat button, which usually cycles through the three modes, only exposes the two mentioned above. With `spotify-tui`, switching the repeat mode to `track` works (as in: it shows `Repeat: Track` in the UI), but the text resets itself after a few seconds.

I'm not sure wether this is a regression or was always the behaviour, but judging by the two recent reports in https://github.com/Spotifyd/spotifyd/issues/1071 and that I could not yet find any other issue that describes this, it might be a change on the Spotify side, which requires changes in `librespot`.

**Note:** This is only an issue with librespot, not with Spotify Connect devices in general, since I seem to be able to set the repeat mode to `track` on an "official" Connect device.

Let me know if you need any further details. Thanks!

**Comment by roderickvd** [comment] 2022-04-12 19:45
Duplicate of #19

**Closed by roderickvd** 2022-04-12 19:45 UTC

**Comment by eladyn** [comment] 2022-04-12 19:57
Oh, right. I read through that issue, but it seemed different. Should have read more carefully. :sweat_smile:

**Comment by roderickvd** [comment] 2022-04-12 19:58
No worries, thanks for your extensive description too.
