### ISSUE TITLE
Possible ratelimiting introduced by Spotify

### ISSUE THREAD

**Issue by x528491x** [librespot-org/librespot#1319] opened 2024-08-31 01:55 UTC
When shuffling between tracks too fast, I get the error message below while fetching the audio_key for decryption:

`Error { kind: Unavailable, error: AesKey }`

I had not run into such errors a few days ago, and I have seen other people report the same error recently on discord servers.

**Comment by x528491x** [comment] 2024-09-08 04:11
Spotify might be sending a retry after header like it does for most rate limited endpoints.

The header, if it is sent, needs to be exposed.

**Comment by roderickvd** [comment] 2024-09-08 10:27
IIRC I did implement "retry after" in dev, no?

**Comment by x528491x** [comment] 2024-09-08 11:14
A retry mechanism for the audio keys is direly needed as the rate limiting almost makes my entire project unusable.

**Comment by roderickvd** [comment] 2024-09-08 11:16
If you're a developer yourself,  a PR would be welcome.

**Comment by x528491x** [comment] 2024-09-08 11:21
> If you're a developer yourself,  a PR would be welcome. 

I'm a golang developer and my first and only rust project is using this library 😅

I do intend to learn rust and contribute to this project, but for now I'll wait for someone more knowledgeable and well versed with the project's codebase to work on it.

**Comment by michaelherger** [comment] 2024-09-08 11:35
Is there a good reason for the rate limiting? Or could the reason for the rate limiting be addressed instead of adding retry?

**Comment by x528491x** [comment] 2024-09-08 11:56
> Is there a good reason for the rate limiting? Or could the reason for the rate limiting be addressed instead of adding retry?
> 

My project revolves around curating music after experiencing the "vibe" of a song, almost in a speedrun manner. (Might be the most cringe description)

To do so, I let the user quickly shuffle between tracks in a playlist, and automatically jump to a random position (somewhere around the middle of the track) and play it for a couple of seconds, giving the user the option to add it to their playlist should they have liked the preview.

The whole idea is that time is precious and a playlist can never be long enough ;)

As to why Spotify introduced the rate limiting that did not exist before, I do not know why. Probably they just discovered the lapse while pushing the other changes they had made to the API lately.

I cannot really "address" the cause of my project being rate limited due to the very nature of it. However, I'll still be happy to have it working as before while complying to Spotify's rate limit policies which I have yet to see stated with actual limits anywhere on their documentation.

**Comment by michaelherger** [comment] 2024-09-09 03:24
Ok, sounds like a good reason to be rate limited 😄. Your application certainly is not typical behaviour, and from their point of view it might look like someone trying to mass download music files. Why else would a normal user try to get tracks in quick succession? Your application is out of the ordinary. 

Whether they changed rate limiting recently or not, we can only speculate. But if I were a service provider, I'd probably block this kind of pattern, too.

**Comment by x528491x** [comment] 2024-09-09 03:44
> Ok, sounds like a good reason to be rate limited 😄. Your application certainly is not typical behaviour, and from their point of view it might look like someone trying to mass download music files. Why else would a normal user try to get tracks in quick succession? Your application is out of the ordinary. 
> 
> Whether they changed rate limiting recently or not, we can only speculate. But if I were a service provider, I'd probably block this kind of pattern, too.

I do know that my application is in the grey area in regards to spamming requests for tracks one after the other in short intervals.

But that is... kind of the appeal of it. To help the user take shortcuts in the process and save some time.

Sure, I get how Spotify might view my application as a batch downloader of sorts, and I admit that my use case may be mildly abusive, but I want to adhere to their rate limits so as to not face failed requests nor get my account banned.

Retry-After would fix my application:

Once the user requests a shuffle, I'll send a request to fetch the next song,

and if I'm already rate limited, I'll wait for the Retry-After interval to be reached, and until then I'll continue playing the current track and notify the user that the shuffle will be done in x seconds.

**Comment by roderickvd** [comment] 2024-09-09 05:46
In Mercury, which is just TCP-based, there is no retry after header. Until someone adds rate limiting there in librespot (you could mostly copy it from the way it's done with HTTP) I suggest that you do it on the caller end (your end).

**Comment by kingosticks** [comment] 2024-09-09 08:56
> a better fix if we could get the Retry-After header

What header? From where? There are no headers for Mercury requests like this.

I don't recall any rate limited playback issues here but perhaps these are downstream problems from projects doing weird things that we don't hear about.

**Comment by x528491x** [comment] 2024-09-09 09:07
> > a better fix if we could get the Retry-After header
> 
> What header? From where? There are no headers for Mercury requests like this.
> 
> I don't recall any rate limited playback issues here but perhaps these are downstream problems from projects doing weird things that we don't hear about. 

Apologies. I missed roderick's earlier message stating that there are no Retry-After headers.

In that case, I guess I'll just have to modify my code to fetch the preview files and fall back to the actual track if the preview file is not found.

Feel free to close this issue if any retry implementation is not planned for such edge cases.

**Closed** 2024-09-16 17:47 UTC
Labels: bug

**Comment by michaelherger** [comment] 2024-09-25 21:53
FWIW: I'm seeing this here, as I'm trying to skip through a playlist. I could actually imagine this would happen to "real users", too: play playlist; "don't like that track - next"; repeat previous step a few times.

**Comment by kingosticks** [comment] 2024-09-25 22:18
Can someone give me an example of how much skipping needs to be done? I was trying to reproduce this earlier by manually skipping and I failed.

**Comment by michaelherger** [comment] 2024-09-26 05:45
Took me 32 skips. Thought it was fewer yesterday. All I tried was to jump to the end of the list, and clicking the last item in the queue wouldn't do the trick for whatever reason.

Now I'm wondering how long it'll take before I can skip again.

**Comment by x528491x** [comment] 2024-09-26 06:11
> FWIW: I'm seeing this here, as I'm trying to skip through a playlist. I could actually imagine this would happen to "real users", too: play playlist; "don't like that track - next"; repeat previous step a few times.

As I had mentioned in my earlier messages, "real users" are also likely to hit this issue, and everyone would benefit some kind of workaround for this.

However, it has been impossible to decipher the ratelimit. Although, I too hit my errors somewhere around the 32 track mark.

**Comment by PandaWill** [comment] 2024-11-12 15:00
FWIW: real user here, just hit this issue while manually skipping around tracks inside ncpsot.
