### ISSUE TITLE
 Playback crashes when switching users

### ISSUE THREAD

**Issue by mikeszila** [librespot-org/librespot#579] opened 2021-01-24 19:47 UTC
I do not use username or password options when starting librespot.  I can connect to librespot with multiple different clients as long as they are the same user.  If I then try to connect with a client logged in with a different user, librespot crashes.  I don't even have to press play for this to happen.  Below is the only output when this happens.  Previous versions of librespot did not exhibit this behaviour, though I'm not sure when it started.  
```

DEBUG librespot_connect::discovery] Post "/" {}
DEBUG librespot_connect::spirc] drop Spirc[0]
DEBUG librespot_playback::player] Shutting down player thread ...
```

The only way to connect with a different user us to remove the credentials.json file in the cache folder then restart librespot, but then it's locked into whichever client connects next forever.  This makes it difficult for friends and family to make use of librespot.   

I'm not sure if this is the same issue or not.  Other than the title and basic symptoms it looks different to me.  https://github.com/librespot-org/librespot/issues/523  If it matters I use the pipe backend.

**Comment by mikeszila** [comment] 2021-01-27 20:39
Is this considered normal behaviour?  Is there anything else I could provide to help convey the issue?

**Comment by sashahilton00** [comment] 2021-01-30 02:16
Is that built with the latest commit? There were some cache issues that I let slip through in a PR. Doesn't look like the problem that was reported, but deleting credentials.json to resolve suggests it may be related

**Comment by sashahilton00** [comment] 2021-02-06 03:31
I wonder if https://github.com/librespot-org/librespot/blob/f67ceb5f6d955c800564a98f8a4098c7702e8083/connect/src/discovery.rs#L81 is somewhat responsible, in that if a client tries to connect when a user is active, it might send an action such as `logoutUser`, which removes the active user before logging the new one in. Having said that though, I believe account switching should just work, it shouldn't be sticking with one account forever so to speak. We may need to investigate further.

**Comment by roderickvd** [comment] 2021-06-14 10:30
Is this still an issue on vanilla `librespot` (i.e. not repackaged with `ncspot` or `Spotifyd` or the like)? Recently I have tested switching back and forth users and cannot reproduce this.

**Comment by roderickvd** [comment] 2021-08-07 20:19
Closing, no further feedback.

**Closed by roderickvd** 2021-08-07 20:19 UTC
Labels: bug, reverse engineering, can't reproduce
