### ISSUE TITLE
Autoplay problem: mostly it either logs an error, or crashes librespot completely.

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#697] opened 2021-04-15 05:39 UTC
Here is a log from a build I made two days ago with the very latest commit in the ``dev``:

```
[2021-04-14T16:37:18Z INFO  librespot] librespot 0.1.6 4fc3acc (Built on 2021-04-13, Build ID: MJycZChu)
```

Sometimes autoplay works, for example:

```
[2021-04-14T16:41:48Z INFO  librespot_connect::spirc] Fetching autoplay context uri
[2021-04-14T16:41:48Z INFO  librespot_connect::spirc] Autoplay uri resolved to <"spotify:station:playlist:5toumWoSlOyiNooSSlYWSs">
[2021-04-14T16:41:50Z INFO  librespot_connect::spirc] Resolved 50 tracks from <"spotify:playlist:5toumWoSlOyiNooSSlYWSs">
```

That is fine.

Mostly, however, this happens:

```
[2021-04-14T17:59:56Z INFO  librespot_connect::spirc] Fetching autoplay context uri
[2021-04-14T17:59:56Z WARN  librespot_connect::spirc] No autoplay_uri found
[2021-04-14T17:59:56Z ERROR librespot_connect::spirc] AutoplayError: MercuryError
```

I understand that if no ``autoplay_uri`` is found, a warning should be issued, as is, but shouldn't the error after that be handled in the code in a better way, so that it does not error out when no uri was found?

Sometimes, however, this happens:

```
[2021-04-14T19:05:19Z INFO  librespot_connect::spirc] Fetching autoplay context uri
thread 'main' panicked at 'Spotify servers returned an error. Restart librespot.', core/src/mercury/mod.rs:207:13
stack backtrace:
   0:   0x89159c - std::backtrace_rs::backtrace::libunwind::trace::hf6a81b4d2b4f0df0
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0x89159c - std::backtrace_rs::backtrace::trace_unsynchronized::h52cf8205b95b2233
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x89159c - std::sys_common::backtrace::_print_fmt::h8f4da63b843fcffb
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x89159c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h540c5d7f193318fc
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:   0x8bb168 - core::fmt::write::h59f3e48f4ce2ab85
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:   0x889930 - std::io::Write::write_fmt::hfda979d0d2de9cfe
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:   0x89425c - std::sys_common::backtrace::_print::h466acc14bc4eb790
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:   0x89425c - std::sys_common::backtrace::print::h7a73b03b6fa7a33b
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:   0x89425c - std::panicking::default_hook::{{closure}}::hedb34ecea85ab3df
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:   0x893cc4 - std::panicking::default_hook::h2692296964250cbf
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:   0x894a70 - std::panicking::rust_panic_with_hook::hf65504862ea28016
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:   0x6118e0 - std::panicking::begin_panic::{{closure}}::h6097a0e11ffc61e1
  12:   0x611888 - std::sys_common::backtrace::__rust_end_short_backtrace::hde8eaecc98fe6f7b
  13:   0x62a6f4 - std::panicking::begin_panic::hfdf2d7855245d56b
  14:   0x632fc0 - librespot_core::mercury::MercuryManager::dispatch::h6c287b68b6113970
  15:   0x626518 - librespot_core::session::Session::dispatch::h245742834baa7b53
  16:   0x62758c - <librespot_core::session::DispatchTask<S> as core::future::future::Future>::poll::hca1e79bf19f4bac0
  17:   0x62a1dc - <futures_util::future::try_maybe_done::TryMaybeDone<Fut> as core::future::future::Future>::poll::h19cf21dd1dcc3bbf
  18:   0x62c570 - <futures_util::future::try_join::TryJoin<Fut1,Fut2> as core::future::future::Future>::poll::h35570d294ba419f9
  19:   0x617864 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h51799fdc67164ebe
  20:   0x630df8 - tokio::runtime::task::harness::poll_future::h066809ed522dfb05
  21:   0x6310b0 - tokio::runtime::task::harness::Harness<T,S>::poll::hb074813818cc0dfb
  22:   0x464b38 - std::thread::local::LocalKey<T>::with::ha0afcefbb9dfaea5
  23:   0x47b180 - tokio::macros::scoped_tls::ScopedKey<T>::set::h481535fa9fa20129
  24:   0x5049d8 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h379f42410496c7c5
  25:   0x48c8f4 - tokio::runtime::Runtime::block_on::h2ee20ec9ce692a62
  26:   0x4bf4ac - librespot::main::h023cf0353cb3580d
  27:   0x49d858 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7bc0b8772fa22ea4
  28:   0x4f4758 - std::rt::lang_start::{{closure}}::h66654766d7772f90
  29:   0x894e7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h15cbbffc3da2a6a5
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  30:   0x894e7c - std::panicking::try::do_call::h2fe9f7cc2a2b6f6d
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  31:   0x894e7c - std::panicking::try::h3b26117bbc08e219
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  32:   0x894e7c - std::panic::catch_unwind::h497ff6a5154802d0
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  33:   0x894e7c - std::rt::lang_start_internal::hdf965c562224da69
                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  34:   0x4bf570 - main
  35: 0x76c73718 - __libc_start_main
[2021-04-14T19:05:19Z ERROR librespot_connect::spirc] AutoplayError: MercuryError
```

**Comment by Johannesd3** [comment] 2021-04-15 06:15
I can't reproduce this issue. Would you please provide an example how you make this happen?

Also, please try it on 8fe2e01166657c7888eb14e5dc7b755be8a9022f, so we can decide whether the tokio migration is at fault.

**Comment by coderootme** [comment] 2021-04-15 06:22
I will try to reproduce it. The panic does not happen often. Here may be some more data/info for now:

```
[2021-04-14T19:04:59Z ERROR librespot_connect::spirc] AutoplayError: MercuryError
thread 'thread '<unnamed>main' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((178, [0, 8, 0, 0, 0, 0, 0, 0, 2, 183, 1, 0, 1, 0, 61, 10, 54, 104, 109, 58, 47, 47, 109, 101, 116, 97, 100, 97, 116, 97, 47, 51, 47, 116, 114, 97, 99, 107, 47, 99, 57, 97, 52, 51, 48, 99, 53, 100, 102, 54, 49, 52, 101, 97, 49, 98, 57, 100, 53, 101, 50, 101, 55, 51, 49, 48, 98, 49, 102, 101, 54, 26, 3, 71, 69, 84]))called `Result::unwrap()` on an `Err` value: SendError((178, [0, 8, 0, 0, 0, 0, 0, 0, 2, 182, 1, 0, 2, 0, 51, 10, 43, 104, 109, 58, 47, 47, 114, 101, 109, 111, 116, 101, 47, 117, 115, 101, 114, 47, 56, 117, 119, 54, 122, 122, 101, 102, 103, 121, 121, 97, 120, 99, 53, 120, 48, 50, 108, 109, 117, 54, 51, 102, 48, 47, 26, 4, 83, 69, 78, 68, 1, 226, 8, 1, 18, 40, 57, 49, 52, 102, 101, 97, 57, 57, 52, 53, 102, 50, 51, 98, 48, 54, 51, 100, 52, 98, 101, 57, 54, 50, 56, 97, 50, 57, 52, 55, 97, 51, 98, 98, 97, 54, 102, 98, 99, 98, 26, 5, 50, 46, 48, 46, 48, 32, 176, 3, 40, 10, 58, 236, 1, 10, 17, 108, 105, 98, 114, 101, 115, 112, 111, 116, 45, 52, 102, 99, 51, 97, 99, 99, 80, 1, 88, 1, 96, 255, 111, 106, 12, 115, 108, 117, 99, 104, 97, 100, 105, 101, 108, 107, 97, 120, 159, 211, 168, 140, 141, 47, 138, 1, 4, 8, 2, 16, 1, 138, 1, 4, 8, 4, 16, 8, 138, 1, 4, 8, 5, 16, 1, 138, 1, 4, 8, 6, 16, 0, 138, 1, 4, 8, 7, 16, 1, 138, 1, 4, 8, 8, 16, 64, 138, 1, 4, 8, 13, 16, 1, 138, 1, 77, 8, 1, 26, 5, 97, 108, 98, 117, 109, 26, 8, 112, 108, 97, 121, 108, 105, 115, 116, 26, 6, 115, 101, 97, 114, 99, 104, 26, 5, 105, 110, 98, 111, 120, 26, 7, 116, 111, 112, 108, 105, 115, 116, 26, 7, 115, 116, 97, 114, 114, 101, 100, 26, 16, 112, 117, 98, 108, 105, 115, 104, 101, 100, 115, 116, 97, 114, 114, 101, 100, 26, 5, 116, 114, 97, 99, 107, 138, 1, 57, 8, 9, 26, 11, 97, 117, 100, 105, 111, 47, 108, 111, 99, 97, 108, 26, 11, 97, 117, 100, 105, 111, 47, 116, 114, 97, 99, 107, 26, 13, 97, 117, 100, 105, 111, 47, 101, 112, 105, 115, 111, 100, 101, 26, 5, 108, 111, 99, 97, 108, 26, 5, 116, 114, 97, 99, 107, 98, 176, 1, 18, 51, 115, 112, 111, 116, 105, 102, 121, 58, 112, 108, 97, 121, 108, 105, 115, 116, 58, 48, 78, 73, 71, 56, 65, 79, 112, 72, 55, 87, 72, 112, 86, 84, 112, 118, 102, 67, 105, 49, 51, 58, 114, 101, 99, 111, 109, 109, 101, 110, 100, 101, 100, 32, 0, 40, 1, 56, 143, 235, 150, 142, 141, 47, 104, 0, 112, 0, 208, 1, 0, 218, 1, 18, 10, 16, 201, 164, 48, 197, 223, 97, 78, 161, 185, 213, 226, 231, 49, 11, 31, 230, 218, 1, 18, 10, 16, 23, 84, 240, 104, 171, 93, 75, 70, 169, 80, 29, 105, 238, 129, 156, 162, 218, 1, 18, 10, 16, 100, 239, 169, 210, 146, 95, 69, 229, 156, 71, 244, 130, 211, 207, 29, 228, 218, 1, 18, 10, 16, 77, 206, 77, 118, 149, 244, 72, 66, 133, 123, 76, 181, 88, 10, 6, 150, 218, 1, 18, 10, 16, 27, 115, 67, 244, 255, 221, 72, 151, 137, 201, 28, 88, 151, 83, 192, 25, 136, 1, 138, 243, 150, 142, 141, 47]))', ', core/src/session.rscore/src/session.rs::210210::4848
```

**Comment by coderootme** [comment] 2021-04-15 20:14
OK, I know how to reproduce it!

1. Start any official spotify client
2. Go to any playlist that you are the owner of. Scroll down to "Recommended Songs Based on the songs in this playlist"
3. Play any of those songs.

Now librespot crashes completely!

**Comment by Johannesd3** [comment] 2021-04-15 20:41
I just get:
```
[2021-04-15T20:39:53Z INFO  librespot_connect::spirc] Fetching autoplay context uri
[2021-04-15T20:39:53Z WARN  librespot_connect::spirc] No autoplay_uri found
[2021-04-15T20:39:53Z ERROR librespot_connect::spirc] AutoplayError: MercuryError
```
as you describe above.

But it plays the song, no panic, no crash.

**Comment by Johannesd3** [comment] 2021-04-15 20:56
The panic message above is actually two panic messages interleaved:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((178, [0, 8, 0, 0, 0, 0, 0, 0, 2, 183, 1, 0, 1, 0, 61, 10, 54, 104, 109, 58, 47, 47, 109, 101, 116, 97, 100, 97, 116, 97, 47, 51, 47, 116, 114, 97, 99, 107, 47, 99, 57, 97, 52, 51, 48, 99, 53, 100, 102, 54, 49, 52, 101, 97, 49, 98, 57, 100, 53, 101, 50, 101, 55, 51, 49, 48, 98, 49, 102, 101, 54, 26, 3, 71, 69, 84]))', core/src/session.rs:210:48
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((178, [0, 8, 0, 0, 0, 0, 0, 0, 2, 182, 1, 0, 2, 0, 51, 10, 43, 104, 109, 58, 47, 47, 114, 101, 109, 111, 116, 101, 47, 117, 115, 101, 114, 47, 56, 117, 119, 54, 122, 122, 101, 102, 103, 121, 121, 97, 120, 99, 53, 120, 48, 50, 108, 109, 117, 54, 51, 102, 48, 47, 26, 4, 83, 69, 78, 68, 1, 226, 8, 1, 18, 40, 57, 49, 52, 102, 101, 97, 57, 57, 52, 53, 102, 50, 51, 98, 48, 54, 51, 100, 52, 98, 101, 57, 54, 50, 56, 97, 50, 57, 52, 55, 97, 51, 98, 98, 97, 54, 102, 98, 99, 98, 26, 5, 50, 46, 48, 46, 48, 32, 176, 3, 40, 10, 58, 236, 1, 10, 17, 108, 105, 98, 114, 101, 115, 112, 111, 116, 45, 52, 102, 99, 51, 97, 99, 99, 80, 1, 88, 1, 96, 255, 111, 106, 12, 115, 108, 117, 99, 104, 97, 100, 105, 101, 108, 107, 97, 120, 159, 211, 168, 140, 141, 47, 138, 1, 4, 8, 2, 16, 1, 138, 1, 4, 8, 4, 16, 8, 138, 1, 4, 8, 5, 16, 1, 138, 1, 4, 8, 6, 16, 0, 138, 1, 4, 8, 7, 16, 1, 138, 1, 4, 8, 8, 16, 64, 138, 1, 4, 8, 13, 16, 1, 138, 1, 77, 8, 1, 26, 5, 97, 108, 98, 117, 109, 26, 8, 112, 108, 97, 121, 108, 105, 115, 116, 26, 6, 115, 101, 97, 114, 99, 104, 26, 5, 105, 110, 98, 111, 120, 26, 7, 116, 111, 112, 108, 105, 115, 116, 26, 7, 115, 116, 97, 114, 114, 101, 100, 26, 16, 112, 117, 98, 108, 105, 115, 104, 101, 100, 115, 116, 97, 114, 114, 101, 100, 26, 5, 116, 114, 97, 99, 107, 138, 1, 57, 8, 9, 26, 11, 97, 117, 100, 105, 111, 47, 108, 111, 99, 97, 108, 26, 11, 97, 117, 100, 105, 111, 47, 116, 114, 97, 99, 107, 26, 13, 97, 117, 100, 105, 111, 47, 101, 112, 105, 115, 111, 100, 101, 26, 5, 108, 111, 99, 97, 108, 26, 5, 116, 114, 97, 99, 107, 98, 176, 1, 18, 51, 115, 112, 111, 116, 105, 102, 121, 58, 112, 108, 97, 121, 108, 105, 115, 116, 58, 48, 78, 73, 71, 56, 65, 79, 112, 72, 55, 87, 72, 112, 86, 84, 112, 118, 102, 67, 105, 49, 51, 58, 114, 101, 99, 111, 109, 109, 101, 110, 100, 101, 100, 32, 0, 40, 1, 56, 143, 235, 150, 142, 141, 47, 104, 0, 112, 0, 208, 1, 0, 218, 1, 18, 10, 16, 201, 164, 48, 197, 223, 97, 78, 161, 185, 213, 226, 231, 49, 11, 31, 230, 218, 1, 18, 10, 16, 23, 84, 240, 104, 171, 93, 75, 70, 169, 80, 29, 105, 238, 129, 156, 162, 218, 1, 18, 10, 16, 100, 239, 169, 210, 146, 95, 69, 229, 156, 71, 244, 130, 211, 207, 29, 228, 218, 1, 18, 10, 16, 77, 206, 77, 118, 149, 244, 72, 66, 133, 123, 76, 181, 88, 10, 6, 150, 218, 1, 18, 10, 16, 27, 115, 67, 244, 255, 221, 72, 151, 137, 201, 28, 88, 151, 83, 192, 25, 136, 1, 138, 243, 150, 142, 141, 47]))', core/src/session.rs:210:48
```

**Comment by roderickvd** [comment] 2021-08-07 20:17
Closing, can't reproduce and no further feedback.

**Closed by roderickvd** 2021-08-07 20:17 UTC
Labels: bug, can't reproduce
