### ISSUE TITLE
Problems with username and special characters

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#65] opened 2018-01-29 14:34 UTC
<a href="https://github.com/AmelioIO"><img src="https://avatars1.githubusercontent.com/u/25708094?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AmelioIO](https://github.com/AmelioIO)**
_Tuesday Jul 04, 2017 at 14:00 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/210_

----

Hi, 

I have the librespot service up and running and can use it with most usernames, but it won't work with mine. My spotify username contains a "|" and a "!".

I tried escaping it after --username but that doesn't work.

Does anybody now how to fix this?

Thanks

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/awiouy"><img src="https://avatars0.githubusercontent.com/u/9913019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awiouy](https://github.com/awiouy)**
_Thursday Jul 06, 2017 at 20:54 GMT_

----

In Linux use single quotes: --username 'Weird|Name!'

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/AmelioIO"><img src="https://avatars1.githubusercontent.com/u/25708094?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AmelioIO](https://github.com/AmelioIO)**
_Friday Jul 07, 2017 at 10:40 GMT_

----

Thanks for your response. But unfortunatly it won't work with single quotes.

Librespot creates a credentials.json file with my username, but everything after that fails.

Also, when using librespot in discovery mode it will fail cause than there is no place to escape those characters at all. 

I'd be glad to give some more information if needed.

Thanks

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/michaelherger"><img src="https://avatars3.githubusercontent.com/u/2789989?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michaelherger](https://github.com/michaelherger)**
_Tuesday Aug 08, 2017 at 21:08 GMT_

----

Just got a report of a user failing with the dollar sign ($) in the password, another one with spaces.

Can we up the importance of this issue?

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Wednesday Aug 09, 2017 at 01:39 GMT_

----

Spotify won't let me do any of `$ | !` or spaces in a username when making an account.

Do you have more details than "failing" ? Is there an error message ?

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Wednesday Aug 09, 2017 at 01:42 GMT_

----

#23 was supposed to handle cases with usernames with uppercase characters, which should have fixed special characters as well.

**Comment by sashahilton00** [comment] 2018-01-29 14:34
<a href="https://github.com/michaelherger"><img src="https://avatars3.githubusercontent.com/u/2789989?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michaelherger](https://github.com/michaelherger)**
_Wednesday Aug 09, 2017 at 04:28 GMT_

----

@plietar - please see issue #225 (which might be a dupe).

**Comment by michaelherger** [comment] 2018-01-29 19:28
FWIW I just tried @|!, and it all worked if put into single quotes. I previously was testing with double quotes... (and do so in my own code - have to fix that right away :-))

**Comment by ComlOnline** [comment] 2018-01-29 19:47
Wonderful, was that for the username or password?

**Comment by michaelherger** [comment] 2018-01-29 20:06
Can't easily change the username, can I? :-) Tested password only. But in my case it was definitely caused by the incorrect quoting.

**Comment by ComlOnline** [comment] 2018-01-29 20:44
Sorry, sorting through the issues has confused me a tad. I'm going to assume it was the same problem for both and go ahead and close this. Thank you!

**Closed by ComlOnline** 2018-01-29 20:44 UTC
Labels: imported
