### ISSUE TITLE
error audio key 0 2

### ISSUE THREAD

**Issue by acid-sun** [librespot-org/librespot#1348] opened 2024-09-24 07:10 UTC
**Describe the bug**
No sound.

**To reproduce**
1. Launch `librespot` with '-G -C . -O -f F32 -n "librespot-v0.5.0-dev" -b 320 -R 100 -E fixed'

**Log**
[2024-09-24T07:08:13Z INFO  librespot] librespot 0.5.0-dev e02e4ae (Built on 2024-09-24, Build ID: Zxr3FtfU, Profile: release)
[2024-09-24T07:08:13Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Fixed
[2024-09-24T07:08:13Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format F32 and cpal host: WASAPI
[2024-09-24T07:08:13Z INFO  librespot_playback::audio_backend::rodio] Using audio device: Speakers (Realtek(R) Audio)
[2024-09-24T07:08:13Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:4070"
[2024-09-24T07:08:13Z INFO  librespot_core::session] Authenticated as '****' !
[2024-09-24T07:08:13Z INFO  librespot_core::session] Country: "MD"
[2024-09-24T07:08:36Z INFO  librespot_core::spclient] Resolved "gew1-spclient.spotify.com:443" as spclient access point
[2024-09-24T07:08:36Z ERROR librespot_connect::spirc] ContextError: Error { kind: Unknown, error: StatusCode(502) }
[2024-09-24T07:08:36Z INFO  librespot_playback::player] Loading <Man On The Run> with Spotify URI <spotify:track:18iz4TDE2RrdyMa6j9Gua2>
[2024-09-24T07:08:36Z ERROR librespot_core::audio_key] error audio key 0 2
[2024-09-24T07:08:36Z WARN  librespot_playback::player] Unable to load key, continuing without decryption: Service unavailable { audio key error }
[2024-09-24T07:08:39Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: end of stream
[2024-09-24T07:08:39Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:track:18iz4TDE2RrdyMa6j9Gua2")>: ()
[2024-09-24T07:08:39Z INFO  librespot_playback::player] Loading <Café Del Mar - Three 'n One Radio Edit> with Spotify URI <spotify:track:791WQUn8PePLamJVPgGKZC>
[2024-09-24T07:08:39Z ERROR librespot_core::audio_key] error audio key 0 2
[2024-09-24T07:08:39Z WARN  librespot_playback::player] Unable to load key, continuing without decryption: Service unavailable { audio key error }
[2024-09-24T07:08:42Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: end of stream

**Host (what you are running `librespot` on):**
- OS: windows

**Additional context**
Sometimes show only ContextError: Error { kind: Unknown, error: StatusCode(502) }
0.4.2 version had same errors.

**Comment by acid-sun** [comment] 2024-09-24 07:36
on librespot-java same error:
024-09-24 10:35:24,233 ERROR AudioKeyManager:128 - Audio key error, code: 2
2024-09-24 10:35:24,233 ERROR Player:387 - Failed loading track.
xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: AAE6995EFA8840C2BDF919201023D88E, fileId: 78DF20501154A5AEF8EAC5ADA915104C6BDABD30}

**Comment by kingosticks** [comment] 2024-09-24 10:26
That track plays for me with the latest code. Can you provide a debug log?

**Comment by acid-sun** [comment] 2024-09-24 11:25
[2024-09-24T11:23:12Z INFO  librespot_playback::player] Loading <Big Fun (Remastered)> with Spotify URI <spotify:track:62s4BJHLdbyLKqxGWxXGax>
[2024-09-24T11:23:12Z DEBUG librespot_audio::fetch] Downloading file efdb540235de8d16092b666383f4bdc0568bf42a
[2024-09-24T11:23:12Z DEBUG librespot_core::http_client] Requesting https://gew1-spclient.spotify.com:443/storage-resolve/files/audio/interactive/efdb540235de8d16092b666383f4bdc0568bf42a?product=0&country=MD&salt=861299632
[2024-09-24T11:23:12Z TRACE librespot_core::cdn_url] Resolved CDN storage: CdnUrl {
        file_id: FileId(
            Ok(
                "efdb540235de8d16092b666383f4bdc0568bf42a",
            ),
        ),
        urls: MaybeExpiringUrls(
            [
                MaybeExpiringUrl(
                    "https://audio-ak-spotify-com.akamaized.net/audio/efdb540235de8d16092b666383f4bdc0568bf42a?__token__=exp=1727263393~hmac=4f7dd124804d3e24d0dcf7843359ae2cba8a32e156ce0925be8b3d3d930ebc55",
                    Some(
                        Date(
                            2024-09-25 11:18:13.0 +00:00:00,
                        ),
                    ),
                ),
                MaybeExpiringUrl(
                    "https://audio4-fa.scdn.co/audio/efdb540235de8d16092b666383f4bdc0568bf42a?1727263393_w_88Q0TVNx0K-ZKdqs73iqzS_RbPHx72ht91oDIyVy4=",
                    Some(
                        Date(
                            2024-09-25 11:18:13.0 +00:00:00,
                        ),
                    ),
                ),
            ],
        ),
    }
[2024-09-24T11:23:12Z TRACE librespot_audio::fetch] Streaming from https://audio-ak-spotify-com.akamaized.net/audio/efdb540235de8d16092b666383f4bdc0568bf42a?__token__=exp=1727263393~hmac=4f7dd124804d3e24d0dcf7843359ae2cba8a32e156ce0925be8b3d3d930ebc55
[2024-09-24T11:23:13Z ERROR librespot_core::audio_key] error audio key 0 2
[2024-09-24T11:23:13Z WARN  librespot_playback::player] Unable to load key, continuing without decryption: Service unavailable { audio key error }
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 17 ms
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 642 kbps
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 867 kbps
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1232 kbps
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1640 kbps
[2024-09-24T11:23:13Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1950 kbps
[2024-09-24T11:23:14Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:16Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 21 ms
[2024-09-24T11:23:16Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1981 kbps
[2024-09-24T11:23:16Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:16Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1848 kbps
[2024-09-24T11:23:17Z DEBUG librespot_audio::fetch] Downloading file efdb540235de8d16092b666383f4bdc0568bf42a complete
[2024-09-24T11:23:17Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: end of stream
[2024-09-24T11:23:17Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId("spotify:track:62s4BJHLdbyLKqxGWxXGax")>: ()
[2024-09-24T11:23:17Z DEBUG librespot_connect::spirc] Marked <TrackRef { gid: Some([198, 112, 229, 92, 125, 73, 79, 35, 131, 215, 116, 144, 117, 74, 199, 45]), uri: None, queued: None, context: Some("NonPlayable"), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }> at 10 as NonPlayable
[2024-09-24T11:23:17Z DEBUG librespot_playback::player] command=Preload(SpotifyId("spotify:track:70XO8AQAspnHLBxzNT83wL"))
[2024-09-24T11:23:17Z DEBUG librespot_playback::player] Preloading track
[2024-09-24T11:23:17Z DEBUG librespot_core::http_client] Requesting https://gew1-spclient.spotify.com:443/metadata/4/track/e6825b7c01bc4f199adc367e3c9b494b?product=0&country=MD&salt=474964668
[2024-09-24T11:23:17Z TRACE librespot_metadata] Received metadata: Track {
        gid: Some(
            [
                230,
                130,
                91,
                124,
                1,
                188,
                79,
                25,
                154,
                220,
                54,
                126,
                60,
                155,
                73,
                75,
            ],
        ),
        name: Some(
            "Welcome To The Jungle - Andrea Oliva Remix",
        ),
        album: MessageField(
            Some(
                Album {
                    gid: Some(
                        [
                            150,
                            213,
                            6,
                            163,
                            217,
                            77,
                            66,
                            180,
                            144,
                            185,
                            22,
                            101,
                            60,
                            4,
                            26,
                            168,
                        ],
                    ),
                    name: Some(
                        "House Top 1000 (Mini Mix 001)",
                    ),
                    artist: [
                        Artist {
                            gid: Some(
                                [
                                    25,
                                    51,
                                    78,
                                    175,
                                    250,
                                    63,
                                    79,
                                    34,
                                    130,
                                    226,
                                    81,
                                    227,
                                    102,
                                    17,
                                    226,
                                    111,
                                ],
                            ),
                            name: Some(
                                "Various Artists",
                            ),
                            popularity: None,
                            top_track: [],
                            album_group: [],
                            single_group: [],
                            compilation_group: [],
                            appears_on_group: [],
                            genre: [],
                            external_id: [],
                            portrait: [],
                            biography: [],
                            activity_period: [],
                            restriction: [],
                            related: [],
                            is_portrait_album_cover: None,
                            portrait_group: MessageField(
                                None,
                            ),
                            sale_period: [],
                            availability: [],
                            special_fields: SpecialFields {
                                unknown_fields: UnknownFields {
                                    fields: None,
                                },
                                cached_size: CachedSize {
                                    size: 0,
                                },
                            },
                        },
                    ],
                    type_: None,
                    label: Some(
                        "ARVA",
                    ),
                    date: MessageField(
                        Some(
                            Date {
                                year: Some(
                                    2018,
                                ),
                                month: Some(
                                    3,
                                ),
                                day: Some(
                                    16,
                                ),
                                hour: None,
                                minute: None,
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                        ),
                    ),
                    popularity: None,
                    genre: [],
                    cover: [],
                    external_id: [],
                    disc: [],
                    review: [],
                    copyright: [],
                    restriction: [],
                    related: [],
                    sale_period: [],
                    cover_group: MessageField(
                        Some(
                            ImageGroup {
                                image: [
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                30,
                                                2,
                                                148,
                                                215,
                                                218,
                                                68,
                                                245,
                                                145,
                                                135,
                                                135,
                                                150,
                                                162,
                                                37,
                                                63,
                                            ],
                                        ),
                                        size: Some(
                                            DEFAULT,
                                        ),
                                        width: Some(
                                            300,
                                        ),
                                        height: Some(
                                            300,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                72,
                                                81,
                                                148,
                                                215,
                                                218,
                                                68,
                                                245,
                                                145,
                                                135,
                                                135,
                                                150,
                                                162,
                                                37,
                                                63,
                                            ],
                                        ),
                                        size: Some(
                                            SMALL,
                                        ),
                                        width: Some(
                                            64,
                                        ),
                                        height: Some(
                                            64,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                    Image {
                                        file_id: Some(
                                            [
                                                171,
                                                103,
                                                97,
                                                109,
                                                0,
                                                0,
                                                178,
                                                115,
                                                148,
                                                215,
                                                218,
                                                68,
                                                245,
                                                145,
                                                135,
                                                135,
                                                150,
                                                162,
                                                37,
                                                63,
                                            ],
                                        ),
                                        size: Some(
                                            LARGE,
                                        ),
                                        width: Some(
                                            640,
                                        ),
                                        height: Some(
                                            640,
                                        ),
                                        special_fields: SpecialFields {
                                            unknown_fields: UnknownFields {
                                                fields: None,
                                            },
                                            cached_size: CachedSize {
                                                size: 0,
                                            },
                                        },
                                    },
                                ],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                        ),
                    ),
                    original_title: None,
                    version_title: None,
                    type_str: None,
                    availability: [],
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: Some(
                                {
                                    25: UnknownValues {
                                        fixed32: [],
                                        fixed64: [],
                                        varint: [],
                                        length_delimited: [
                                            [
                                                10,
                                                16,
                                                105,
                                                158,
                                                178,
                                                128,
                                                79,
                                                4,
                                                72,
                                                81,
                                                165,
                                                35,
                                                178,
                                                22,
                                                61,
                                                48,
                                                174,
                                                123,
                                            ],
                                        ],
                                    },
                                },
                            ),
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ),
        ),
        artist: [
            Artist {
                gid: Some(
                    [
                        175,
                        86,
                        27,
                        226,
                        21,
                        8,
                        79,
                        182,
                        129,
                        184,
                        182,
                        202,
                        203,
                        193,
                        86,
                        185,
                    ],
                ),
                name: Some(
                    "Thick Dick",
                ),
                popularity: None,
                top_track: [],
                album_group: [],
                single_group: [],
                compilation_group: [],
                appears_on_group: [],
                genre: [],
                external_id: [],
                portrait: [],
                biography: [],
                activity_period: [],
                restriction: [],
                related: [],
                is_portrait_album_cover: None,
                portrait_group: MessageField(
                    None,
                ),
                sale_period: [],
                availability: [],
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            Artist {
                gid: Some(
                    [
                        210,
                        22,
                        32,
                        191,
                        84,
                        237,
                        66,
                        37,
                        144,
                        19,
                        85,
                        94,
                        101,
                        62,
                        87,
                        241,
                    ],
                ),
                name: Some(
                    "Andrea Oliva",
                ),
                popularity: None,
                top_track: [],
                album_group: [],
                single_group: [],
                compilation_group: [],
                appears_on_group: [],
                genre: [],
                external_id: [],
                portrait: [],
                biography: [],
                activity_period: [],
                restriction: [],
                related: [],
                is_portrait_album_cover: None,
                portrait_group: MessageField(
                    None,
                ),
                sale_period: [],
                availability: [],
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        number: Some(
            2,
        ),
        disc_number: Some(
            2,
        ),
        duration: Some(
            182857,
        ),
        popularity: Some(
            12,
        ),
        explicit: None,
        external_id: [
            ExternalId {
                type_: Some(
                    "isrc",
                ),
                id: Some(
                    "GBZ9E1708203",
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        restriction: [],
        file: [
            AudioFile {
                file_id: Some(
                    [
                        81,
                        101,
                        25,
                        166,
                        220,
                        237,
                        239,
                        102,
                        206,
                        212,
                        50,
                        221,
                        228,
                        115,
                        45,
                        55,
                        192,
                        240,
                        98,
                        208,
                    ],
                ),
                format: Some(
                    OGG_VORBIS_320,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        130,
                        108,
                        168,
                        107,
                        98,
                        139,
                        201,
                        122,
                        46,
                        127,
                        232,
                        118,
                        25,
                        153,
                        196,
                        63,
                        94,
                        118,
                        19,
                        253,
                    ],
                ),
                format: Some(
                    OGG_VORBIS_160,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        45,
                        237,
                        4,
                        216,
                        233,
                        68,
                        2,
                        213,
                        167,
                        143,
                        1,
                        238,
                        76,
                        105,
                        245,
                        7,
                        226,
                        230,
                        220,
                        79,
                    ],
                ),
                format: Some(
                    OGG_VORBIS_96,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        207,
                        196,
                        152,
                        199,
                        8,
                        224,
                        140,
                        27,
                        232,
                        246,
                        146,
                        141,
                        11,
                        184,
                        65,
                        206,
                        13,
                        251,
                        141,
                        194,
                    ],
                ),
                format: Some(
                    OTHER5,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        165,
                        139,
                        115,
                        230,
                        221,
                        69,
                        122,
                        67,
                        187,
                        135,
                        60,
                        248,
                        220,
                        138,
                        191,
                        231,
                        57,
                        156,
                        69,
                        173,
                    ],
                ),
                format: Some(
                    AAC_320,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        71,
                        16,
                        211,
                        37,
                        146,
                        174,
                        168,
                        247,
                        44,
                        134,
                        213,
                        93,
                        170,
                        116,
                        81,
                        240,
                        0,
                        9,
                        88,
                        197,
                    ],
                ),
                format: Some(
                    MP4_128,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        200,
                        249,
                        198,
                        89,
                        0,
                        155,
                        136,
                        230,
                        211,
                        128,
                        15,
                        14,
                        47,
                        193,
                        90,
                        72,
                        141,
                        151,
                        146,
                        86,
                    ],
                ),
                format: Some(
                    AAC_160,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            AudioFile {
                file_id: Some(
                    [
                        92,
                        91,
                        84,
                        141,
                        203,
                        83,
                        9,
                        18,
                        105,
                        216,
                        220,
                        53,
                        101,
                        124,
                        244,
                        229,
                        104,
                        125,
                        65,
                        17,
                    ],
                ),
                format: Some(
                    AAC_24,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        alternative: [],
        sale_period: [],
        preview: [
            AudioFile {
                file_id: Some(
                    [
                        234,
                        214,
                        200,
                        17,
                        16,
                        20,
                        195,
                        9,
                        67,
                        75,
                        227,
                        137,
                        49,
                        233,
                        55,
                        82,
                        221,
                        224,
                        208,
                        14,
                    ],
                ),
                format: Some(
                    MP3_96,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        tags: [],
        earliest_live_timestamp: Some(
            1521111600,
        ),
        has_lyrics: None,
        availability: [],
        licensor: MessageField(
            Some(
                Licensor {
                    uuid: Some(
                        [
                            105,
                            158,
                            178,
                            128,
                            79,
                            4,
                            72,
                            81,
                            165,
                            35,
                            178,
                            22,
                            61,
                            48,
                            174,
                            123,
                        ],
                    ),
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: None,
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ),
        ),
        language_of_performance: [
            "zxx",
        ],
        content_rating: [],
        original_title: Some(
            "Welcome To The Jungle",
        ),
        version_title: Some(
            "Andrea Oliva Remix",
        ),
        artist_with_role: [
            ArtistWithRole {
                artist_gid: Some(
                    [
                        175,
                        86,
                        27,
                        226,
                        21,
                        8,
                        79,
                        182,
                        129,
                        184,
                        182,
                        202,
                        203,
                        193,
                        86,
                        185,
                    ],
                ),
                artist_name: Some(
                    "Thick Dick",
                ),
                role: Some(
                    ARTIST_ROLE_MAIN_ARTIST,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
            ArtistWithRole {
                artist_gid: Some(
                    [
                        210,
                        22,
                        32,
                        191,
                        84,
                        237,
                        66,
                        37,
                        144,
                        19,
                        85,
                        94,
                        101,
                        62,
                        87,
                        241,
                    ],
                ),
                artist_name: Some(
                    "Andrea Oliva",
                ),
                role: Some(
                    ARTIST_ROLE_REMIXER,
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ],
        special_fields: SpecialFields {
            unknown_fields: UnknownFields {
                fields: Some(
                    {
                        36: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    115,
                                    112,
                                    111,
                                    116,
                                    105,
                                    102,
                                    121,
                                    58,
                                    116,
                                    114,
                                    97,
                                    99,
                                    107,
                                    58,
                                    51,
                                    49,
                                    117,
                                    68,
                                    105,
                                    50,
                                    78,
                                    100,
                                    83,
                                    103,
                                    103,
                                    79,
                                    55,
                                    120,
                                    98,
                                    73,
                                    51,
                                    73,
                                    113,
                                    110,
                                    79,
                                    109,
                                ],
                            ],
                        },
                        39: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    10,
                                    2,
                                    8,
                                    0,
                                ],
                            ],
                        },
                        24: UnknownValues {
                            fixed32: [],
                            fixed64: [],
                            varint: [],
                            length_delimited: [
                                [
                                    10,
                                    16,
                                    2,
                                    214,
                                    109,
                                    131,
                                    33,
                                    209,
                                    68,
                                    240,
                                    178,
                                    252,
                                    44,
                                    233,
                                    222,
                                    136,
                                    146,
                                    86,
                                ],
                            ],
                        },
                    },
                ),
            },
            cached_size: CachedSize {
                size: 0,
            },
        },
    }
[2024-09-24T11:23:17Z INFO  librespot_playback::player] Loading <Welcome To The Jungle - Andrea Oliva Remix> with Spotify URI <spotify:track:70XO8AQAspnHLBxzNT83wL>
[2024-09-24T11:23:17Z DEBUG librespot_audio::fetch] Downloading file 516519a6dcedef66ced432dde4732d37c0f062d0
[2024-09-24T11:23:17Z DEBUG librespot_core::http_client] Requesting https://gew1-spclient.spotify.com:443/storage-resolve/files/audio/interactive/516519a6dcedef66ced432dde4732d37c0f062d0?product=0&country=MD&salt=4103606123
[2024-09-24T11:23:17Z TRACE librespot_core::cdn_url] Resolved CDN storage: CdnUrl {
        file_id: FileId(
            Ok(
                "516519a6dcedef66ced432dde4732d37c0f062d0",
            ),
        ),
        urls: MaybeExpiringUrls(
            [
                MaybeExpiringUrl(
                    "https://audio-ak-spotify-com.akamaized.net/audio/516519a6dcedef66ced432dde4732d37c0f062d0?__token__=exp=1727263398~hmac=57aefe470dd42ec10fbe2136f59a255d24fed951447f088d6f07f0e752824873",
                    Some(
                        Date(
                            2024-09-25 11:18:18.0 +00:00:00,
                        ),
                    ),
                ),
                MaybeExpiringUrl(
                    "https://audio4-fa.scdn.co/audio/516519a6dcedef66ced432dde4732d37c0f062d0?1727263398_qWlsUP3OShqrFCkXuujlhFEmrFmjcHtelVFUGEo0mCw=",
                    Some(
                        Date(
                            2024-09-25 11:18:18.0 +00:00:00,
                        ),
                    ),
                ),
            ],
        ),
    }
[2024-09-24T11:23:17Z TRACE librespot_audio::fetch] Streaming from https://audio-ak-spotify-com.akamaized.net/audio/516519a6dcedef66ced432dde4732d37c0f062d0?__token__=exp=1727263398~hmac=57aefe470dd42ec10fbe2136f59a255d24fed951447f088d6f07f0e752824873
[2024-09-24T11:23:18Z ERROR librespot_core::audio_key] error audio key 0 2
[2024-09-24T11:23:18Z WARN  librespot_playback::player] Unable to load key, continuing without decryption: Service unavailable { audio key error }
[2024-09-24T11:23:18Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:18Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 648 kbps
[2024-09-24T11:23:18Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 852 kbps
[2024-09-24T11:23:19Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1312 kbps
[2024-09-24T11:23:19Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 18 ms
[2024-09-24T11:23:19Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1680 kbps
[2024-09-24T11:23:19Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1932 kbps
[2024-09-24T11:23:19Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:20Z TRACE librespot_audio::fetch::receive] Throughput now estimated as: 1927 kbps
[2024-09-24T11:23:21Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 16 ms
[2024-09-24T11:23:21Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 18 ms
[2024-09-24T11:23:21Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:22Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 17 ms
[2024-09-24T11:23:22Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 14 ms
[2024-09-24T11:23:22Z TRACE librespot_audio::fetch::receive] Time to first byte now estimated as: 16 ms
[2024-09-24T11:23:22Z DEBUG librespot_audio::fetch] Downloading file 516519a6dcedef66ced432dde4732d37c0f062d0 complete
[2024-09-24T11:23:22Z ERROR librespot_playback::player] Unable to read audio file: Symphonia Decoder Error: end of stream
[2024-09-24T11:23:22Z DEBUG librespot_playback::player] Unable to preload SpotifyId("spotify:track:70XO8AQAspnHLBxzNT83wL")

**Comment by acid-sun** [comment] 2024-09-24 11:45
Another track...
[librespot_debug2.txt](https://github.com/user-attachments/files/17113951/librespot_debug2.txt)

**Comment by x528491x** [comment] 2024-09-25 03:57
> debug log: [librespot_debug.txt](https://github.com/user-attachments/files/17113765/librespot_debug.txt)
> The problem appears after quickly switching tracks
> 

Duplicate of #1319

**Closed** 2024-09-25 05:07 UTC
Labels: bug
