### ISSUE TITLE
 undefined reference to `llvm.x86.addcarry.64' on debian buster

### ISSUE THREAD

**Issue by christf** [librespot-org/librespot#557] opened 2020-12-31 14:45 UTC
compiling version 0adb8516a65f551211a9ce78c2d822b85454546c on buster fails with
```
cc --version
cc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

christof@build:~/librespot$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

christof@build:~/librespot$ rustc --version
rustc 1.41.1
```

The error message is:
```
   Compiling librespot-core v0.1.3 (/home/christof/librespot/core)
   Compiling librespot-audio v0.1.3 (/home/christof/librespot/audio)
   Compiling librespot-metadata v0.1.3 (/home/christof/librespot/metadata)
   Compiling librespot-playback v0.1.3 (/home/christof/librespot/playback)
   Compiling librespot-connect v0.1.3 (/home/christof/librespot/connect)
   Compiling librespot v0.1.3 (/home/christof/librespot)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o" "-o" "/home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/christof/librespot/target/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustcX0FmzN/libbacktrace_sys-2b9293c7b8f41cd3.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-a5f50861fed71e63.rlib" "-Wl,-Bdynamic" "-lasound" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `<num_bigint::biguint::BigUint as core::ops::arith::Add<&num_bigint::biguint::BigUint>>::add':
          librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0xa7): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0x115): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0x1b9): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0x229): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0x248): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o:librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Add$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$3add17h32ddd009c8dee726E+0x346): more undefined references to `llvm.x86.addcarry.64' follow
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `<num_bigint::biguint::BigUint as core::ops::arith::SubAssign<&num_bigint::biguint::BigUint>>::sub_assign':
          librespot.2euxypc2-cgu.6:(.text._ZN116_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..SubAssign$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$10sub_assign17hc19fdd40e107d0e9E+0x6f): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN116_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..SubAssign$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$10sub_assign17hc19fdd40e107d0e9E+0xca): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN116_$LT$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..SubAssign$LT$$RF$num_bigint..biguint..BigUint$GT$$GT$10sub_assign17hc19fdd40e107d0e9E+0x106): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `<&num_bigint::biguint::BigUint as core::ops::arith::Sub<num_bigint::biguint::BigUint>>::sub':
          librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$$RF$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Sub$LT$num_bigint..biguint..BigUint$GT$$GT$3sub17h510083729c18f3b7E+0x98): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$$RF$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Sub$LT$num_bigint..biguint..BigUint$GT$$GT$3sub17h510083729c18f3b7E+0x10c): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o:librespot.2euxypc2-cgu.6:(.text._ZN110_$LT$$RF$num_bigint..biguint..BigUint$u20$as$u20$core..ops..arith..Sub$LT$num_bigint..biguint..BigUint$GT$$GT$3sub17h510083729c18f3b7E+0x1bd): more undefined references to `llvm.x86.subborrow.64' follow
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `_ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827':
          librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x1c5): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x205): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x390): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0xe57): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0xeb2): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o:librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0xf02): more undefined references to `llvm.x86.addcarry.64' follow
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `_ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827':
          librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x39e7): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x3a53): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms4mac317hbf30062440c4d6c2E.llvm.677551670652487827+0x3ab8): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `num_bigint::biguint::algorithms::sub_sign':
          librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms8sub_sign17hb8b20674cf81a27cE+0x1dc): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms8sub_sign17hb8b20674cf81a27cE+0x235): undefined reference to `llvm.x86.subborrow.64'
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o:librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms8sub_sign17hb8b20674cf81a27cE+0x27c): more undefined references to `llvm.x86.subborrow.64' follow
          /usr/bin/ld: /home/christof/librespot/target/release/deps/librespot-5b93096c48f4124f.librespot.2euxypc2-cgu.6.rcgu.o: in function `num_bigint::biguint::algorithms::div_rem_core':
          librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms12div_rem_core17hffb51c4bf0711330E+0x3f5): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms12div_rem_core17hffb51c4bf0711330E+0x450): undefined reference to `llvm.x86.addcarry.64'
          /usr/bin/ld: librespot.2euxypc2-cgu.6:(.text._ZN10num_bigint7biguint10algorithms12div_rem_core17hffb51c4bf0711330E+0x4a5): undefined reference to `llvm.x86.addcarry.64'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `librespot`.

```

On https://github.com/rust-lang/rust/issues/47493 I found that enabling lto might fix the problem so I tried that - the output is the same though. What could I try next?

**Comment by ashthespy** [comment] 2020-12-31 16:36
Why are you building directly with `rustc`? 
PS: Dupe of  https://github.com/librespot-org/librespot/issues/555

**Comment by christf** [comment] 2021-01-02 16:09
I am not directly building with rustc but with cargo instead. As suggested in #555 I supplied --locked but that did not change the behavior:

```
 cargo build --locked --release
```

**Comment by ashthespy** [comment] 2021-01-02 18:04
Are you sure this is on a fresh checkout?

**Comment by christf** [comment] 2021-01-07 14:20
this was built with 414383db18a95af76359ac0adb53cbd4f78b52ce. With 06f5aa9c907f6702ecba4147d6291c1cc448b295 it still yields the same result.

**Comment by ashthespy** [comment] 2021-01-07 15:19
Sorry, I don't follow - are you saying  with a fresh checkout and `--locked`, https://github.com/librespot-org/librespot/commit/414383db18a95af76359ac0adb53cbd4f78b52ce build fine, but  https://github.com/librespot-org/librespot/commit/06f5aa9c907f6702ecba4147d6291c1cc448b295 doesn't? 
If so, then probably in all the version bumping b/w the commits, some `Cargo.lock` gremlins crept it..

**Comment by christf** [comment] 2021-01-07 15:46
the error message appears no matter whether --locked is specified or not.

**Comment by sashahilton00** [comment] 2021-01-19 02:11
This is indeed a dupe of #555, please move discussion there.

**Closed by sashahilton00** 2021-01-19 02:11 UTC
